sonar.projectKey=devsecops-cicd-platform
sonar.projectName=DevSecOps CI/CD Platform
sonar.sources=app/src
sonar.tests=app/test
sonar.test.inclusions=app/test/**/*.test.js
sonar.javascript.lcov.reportPaths=app/coverage/lcov.info
sonar.qualitygate.wait=true
